name: Vavoo Güncelleyici

on:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu al
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Tüm commit geçmişini al

    - name: Python kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli paketleri yükle
      run: pip install requests APScheduler m3u8

    - name: Botu çalıştır
      run: python bot.py

    - name: Değişiklik kontrolü
      id: check-changes
      run: |
        git diff --exit-code vavooall.m3u || echo "changed=true" >> $GITHUB_OUTPUT
        echo "Değişiklik durumu: ${{ steps.check-changes.outputs.changed }}"

    - name: Değişiklikleri commitle
      if: steps.check-changes.outputs.changed == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add vavooall.m3u
        git commit -m "🔄 Otomatik güncelleme: $(date +'%d.%m.%Y %H:%M')"
        git pushfından otomatik güncelleme"
        git push origin main
