name: Run TV Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install packages
      run: |
        pip install requests
        pip install APScheduler
        pip install m3u8
        
    - name: Run bot
      run: python bot.py
      
    - name: Upload playlist
      uses: actions/upload-artifact@v4  # v4'e güncellendi
      with:
        name: playlist
        path: vavooall.m3u
