name: Run TV Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install packages
      run: pip install requests APScheduler m3u8
      
    - name: Run bot
      run: python bot.py
      
    # YENİ EKLENEN ADIM: Dosyayı ana dizine kopyala
    - name: Move file to root
      run: |
        echo "Oluşturulan dosya:"
        ls -la
        mv vavooall.m3u ./ || echo "Dosya taşınamadı"
        
    # YENİ EKLENEN ADIM: Dosyayı repoya ekle
    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git add vavooall.m3u
        git commit -m "Bot tarafından otomatik güncelleme"
        git push origin main
