name: Update Channels

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main  # Önemli: Repoyu alt dizine çek

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: List files (for debugging)
        run: ls -R  # Dizin yapısını göster

      - name: Run script
        working-directory: ./main  # Çalışma dizinini değiştir
        run: python vavoo_updater.py

      - name: Commit and push changes
        working-directory: ./main  # Çalışma dizinini değiştir
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add vavooall.m3u
          git commit -m "🔄 Otomatik güncelleme"
          git push
