name: Update Channels

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python bot  # Dosya adınız "bot" olduğu için

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add vavooall.m3u
          git commit -m "🔄 Otomatik güncelleme"
          git push
